version: "3.7"
services:
  vault:
    image: vault:1.2.3
    container_name: my_vault
    volumes:
      - ./vault/config:/vault/config:rw
      - ./vault/policies:/vault/policies:rw
      - ./vault/file:/vault/file:rw
      - ./vault/logs:/vault/logs:rw
    environment:
      #- VAULT_DEV_LISTEN_ADDRESS = "http://127.0.0.1:8200"
      #- VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
#      - VAULT_API_ADDR=http://0.0.0.0:8200
      #      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    command: server -dev # -config=/vault/config/vault-config.json
    ports:
      - 8200:8200
  consul:
    container_name: my_consul
    image: consul:latest
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
      - ./consul/data:/consul/data
    healthcheck:
      test: ['CMD', '/bin/sh', '-c', 'curl -sfLo /dev/null http://127.0.0.1:8500/v1/health/node/$$HOSTNAME']
  consul-worker:
    container_name: consul_worker
    image: consul:latest
    command: agent -server -join consul -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
    depends_on:
      - consul