version: "3.7"
services:
  vault:
    image: vault:1.2.3
    container_name: my_vault
    volumes:
      - ./vault/config:/vault/config:rw
      - ./vault/policies:/vault/policies:rw
      - ./vault/file:/vault/file:rw
      - ./vault/logs:/vault/logs:rw
    environment:
      #- VAULT_DEV_LISTEN_ADDRESS = "http://127.0.0.1:8200"
      #- VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
#      - VAULT_API_ADDR=http://0.0.0.0:8200
      #      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/vault-config.json
    ports:
      - 8200:8200